### ISSUE TITLE
Where is the original SVN?

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/someNA#1]
@jmcejuela donde puedo encontrar el repositorio svn de someNA? Busqué por las fuentes que pusiste (https://www.predictprotein.org/, https://rostlab.org/owiki/index.php/Packages, https://rostlab.org/resources/web-services ) pero lo unico que encontré fue en PredictProtein:

> protein-DNA binding sites (DISIS & SomeNA to be released shortly)

Graciaaaaaaaasss :)

**Comment by juanmirocks** [comment]
https://github.com/Rostlab/PP2_CS_WS_2015-16/wiki/HOWTO-access-rostlab-svn-repos
