### ISSUE TITLE
Put simple example(s) in README

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/someNA#10]
- [ ] Write in README a section with 2-3 simple examples for how to run the tool

(If necessary, commit more files into folder `examples/`

FYI I tested the docker image and runs perfectly. Great job!

**Comment by sacdallago** [comment]
#docker thanks
#examples will do

**Comment by sacdallago** [comment]
https://github.com/Rostlab/someNA/blob/develop/README.md
