### ISSUE TITLE
Missing instructions for simple installation in .pack.sh

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/someNA#12]
Default debian wheezy doesn't have some essential tools. You must instruct the user to do:

```
sudo apt-get install devscripts build-essential automake
```

**Comment by sacdallago** [comment]
https://github.com/Rostlab/someNA/blob/develop/README.md#basic-installation section Requirements and the first paragraph of installation?
Alright, I don't mention the whole `supo apt-get...`, but should I @jmcejuela ?  
I basically just took whatever we do in the Dockerfile and tried to bring it to the bare essentials

**Comment by juanmirocks** [comment]
Yes, mention it. Both ways of installation are different and both must work as is for dummies. That is for me.

**Comment by sacdallago** [comment]
https://github.com/Rostlab/someNA/blob/develop/README.md#basic-installation

**Comment by juanmirocks** [comment]
:+1:
