### ISSUE TITLE
Signature bug when running pack.sh

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/someNA#13]
``` shell
Finished running lintian.
Now signing changes and any dsc files...
 signfile somena_1.0.1.dsc Guy Yachdav <gyachdav@rostlab.org>
gpg: directory `/home/vagrant/.gnupg' created
gpg: new configuration file `/home/vagrant/.gnupg/gpg.conf' created
gpg: WARNING: options in `/home/vagrant/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/home/vagrant/.gnupg/secring.gpg' created
gpg: keyring `/home/vagrant/.gnupg/pubring.gpg' created
gpg: skipped "Guy Yachdav <gyachdav@rostlab.org>": secret key not available
gpg: /tmp/debsign.lAbIRbW2/somena_1.0.1.dsc: clearsign failed: secret key not available
debsign: gpg error occurred!  Aborting....
debuild: fatal error at line 1278:
running debsign failed
```

**Comment by sacdallago** [comment]
It is expected!

It is actually an interesting error, it seems to be something related to the system wide configuration of debuild/debsign with respect to the configuration variable given in the repository (somewhere, I don't know where actually). Main source of this idea is http://ubuntuforums.org/showthread.php?t=2172946

IMPORTANT is: It occurred to me yesterday as well when I was testing it out, but this doesn't harm the rest of the installation process.

**Comment by juanmirocks** [comment]
In another repo I am simply fine if the installation instructions indeed say to ignore a possible signature error. 

So please put that into the README and close issue :)

**Comment by sacdallago** [comment]
Saw it in MetaStudent as well yesterday :P ok, will change the Readme
