### ISSUE TITLE
Write mini intro to docker on course Wiki

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/someNA#3]
- [ ] Show advantages or disadvantages vs Vagrant ? (you explained the difference in the presentation)

**Comment by juanmirocks** [comment]
Was this done? A very minimal thing is sufficient.

**Comment by sacdallago** [comment]
Gonna do that after the 25th! :D just need to remember what we discussed about yesterday during the party :P

**Comment by juanmirocks** [comment]
My understanding:
- Docker is for creating discrete single tools packaged with all needed dependencies. This works very much as the Unix philosophy, to create tools that do one thing only, with the distinction that the tools' dependencies are all resolved in the docker images.
- Vagrant is for creating full virtual machines that will often contain multiple tools. Vagrant simplifies the management of virtual machines by interfacing with different virtual machine providers such as VirtualBox or VMWare

**Comment by sacdallago** [comment]
https://github.com/Rostlab/PP2_CS_WS_2015-16/wiki/Docker-and-Virtual-Machines

**Comment by sacdallago** [comment]
<3 tortillas
