### ISSUE TITLE
Get access to Peter's Thesis

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/someNA#6]
Tell me if you need it

**Comment by ghost** [comment]
Oh yes, we do need it!

**Comment by juanmirocks** [comment]
:+1: I wrote him an email about this. Bug me again if you have the thesis in a few days.

**Comment by juanmirocks** [comment]
[thesis-2.pdf](https://github.com/Rostlab/someNA/files/55241/thesis-2.pdf)

There you go guys! @dmitry-n @sacdallago
