### ISSUE TITLE
The script configure does not exit

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/someNA#8]
I don't find that file, only `configure.ac`

Fix this in README

**Comment by sacdallago** [comment]
That's one of the things you need to look up on the advanced install. Configure is generated by a library called `autoconf`, as the config is specific to your environment.

**Comment by juanmirocks** [comment]
I guessed. But whatever it's strictly necessary to install the tool, put it in the simple README instructions, not only in the advanced ones.

**Comment by sacdallago** [comment]
https://github.com/Rostlab/someNA/blob/develop/README.md
