### ISSUE TITLE
Register on Elixir

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/someNA#9]
- [x] Register
- [x] Put in README header

**Comment by sacdallago** [comment]
You mean this? https://bio.tools/

**Comment by juanmirocks** [comment]
:+1: 

Use `Rostlab` as the affiliation and put this repo's link as source

**Comment by juanmirocks** [comment]
Where is the link on the README ?

**Comment by sacdallago** [comment]
I'm sorry, I oversaw that point.
Now it should be ok https://github.com/Rostlab/someNA/blob/develop/README.md :)

**Comment by juanmirocks** [comment]
So much thinking about #tortillas is not good for you.
